### ISSUE TITLE
Allow control of delay before admin bar disappears.

### ISSUE THREAD

**Issue by ChrisFlannagan** [bamadesigner/show-me-the-admin#1]
It would be cool if I could control how long the admin bar lingers for before it fades back up.  Also, it would be cool if I could have the option for it not to fade when my mouse is over it. #Request

**Comment by bamadesigner** [comment]
Chris, I added this awesome request. The code is in the master branch. Mind testing it out? You should see 2 new settings: one to set the delay for the button and one to set the delay for hover. Thanks!

**Comment by ChrisFlannagan** [comment]
Seems to be working great, thanks Rachel!!
